server:
  port: 8082

spring:
  application:
    name: authentication-service
  data:
    mongodb:
      uri: mongodb+srv://radek:radek1@test-ukinn.mongodb.net/test?retryWrites=true
      database: test
  security:

    user:
      name: olo
      password: test

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://rmichniewski.eu:8761/eureka}



jwt:
  secret: mySecret
  expiration: 604800

management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

